#!/bin/sh

IMAGE="/tmp/cache/update.zip"
source=$1

mkdir -p /tmp/cache
mount -t ext4 /dev/cache /tmp/cache

rm -f /tmp/cache/*.zip
wget $source -O /tmp/cache/update.zip
sync

if [ ! -f "${IMAGE}" ]; then
  echo "Error: ${IMAGE} not found"
  exit 1
fi

echo -e "--update_package=/cache/update.zip\n--wipe_cache" > /tmp/cache/recovery/command || exit 1

umount /tmp/cache
#mount -o,ro remount /storage

echo "Update firmware"
reboot recovery

